### ISSUE TITLE
Invalid field name (BN)

### ISSUE THREAD

**Issue by yay855** [jackledead/jackledead_armory#4]
This isn't the full list of errors, just every unique wrong flag or field.

 DEBUG    : (json-error)
Json error: C:/Cataclysm/bn/userdata/mods/jackledead_armory/items/gunmod/grip.json:64:26: Invalid or misplaced field name "aim_speed_modifier" in JSON data

    "handling_modifier": 3,
    "dispersion_modifier": -3,
    "aim_speed_modifier":
                         ^
                          14,
    "min_skills": [ [ "weapon", 3 ] ]
  },

 FUNCTION : report_unvisited
 FILE     : D:\a\Cataclysm-BN\Cataclysm-BN\src\json.cpp
 LINE     : 125
 VERSION  : BN d109e74

 DEBUG    : (json-error)
Json error: C:/Cataclysm/bn/userdata/mods/jackledead_armory/items/gunmod/muzzle.json:135:39: Invalid or misplaced field name "shot_spread_multiplier_modifier" in JSON data

    "mod_target_category": [ [ "SHOTGUNS" ] ],
    "install_time": "5 m",
    "shot_spread_multiplier_modifier":
                                      ^
                                       -0.5
  },
  {

 FUNCTION : report_unvisited
 FILE     : D:\a\Cataclysm-BN\Cataclysm-BN\src\json.cpp
 LINE     : 125
 VERSION  : BN d109e74

 DEBUG    : (json-error)
Json error: C:/Cataclysm/bn/userdata/mods/jackledead_armory/items/gunmod/sights.json:39:33: Invalid or misplaced field name "sight_dispersion_modifier" in JSON data

    ],
    "install_time": "4 m",
    "sight_dispersion_modifier":
                                ^
                                 -2,
    "aim_speed_modifier": 4,
    "min_skills": [ [ "weapon", 2 ], [ "gun", 2 ] ],

 FUNCTION : report_unvisited
 FILE     : D:\a\Cataclysm-BN\Cataclysm-BN\src\json.cpp
 LINE     : 125
 VERSION  : BN d109e74

 DEBUG    : (json-error)
Json error: C:/Cataclysm/bn/userdata/mods/jackledead_armory/items/gunmod/sights.json:150:20: Invalid or misplaced field name "variant_type" in JSON data

    "type": "GUNMOD",
    "//variantsInfo": "These variants will be exactly the same as the vanilla improve_sights stat wise",
    "variant_type":
                   ^
                    "generic",
    "variants": [
      {

 FUNCTION : report_unvisited
 FILE     : D:\a\Cataclysm-BN\Cataclysm-BN\src\json.cpp
 LINE     : 125
 VERSION  : BN d109e74

 DEBUG    : (json-error)
Json error: C:/Cataclysm/bn/userdata/mods/jackledead_armory/items/gunmod/sights.json:151:16: Invalid or misplaced field name "variants" in JSON data

    "//variantsInfo": "These variants will be exactly the same as the vanilla improve_sights stat wise",
    "variant_type": "generic",
    "variants":
               ^
                [
      {
        "id": "jkl_jackle_vanilla_improve_sights",

 FUNCTION : report_unvisited
 FILE     : D:\a\Cataclysm-BN\Cataclysm-BN\src\json.cpp
 LINE     : 125
 VERSION  : BN d109e74

 DEBUG    : (json-error)
Json error: C:/Cataclysm/bn/userdata/mods/jackledead_armory/items/gunmod/underbarrel.json:28:20: Invalid or misplaced field name "melee_damage" in JSON data

    "min_skills": [ [ "weapon", 2 ] ],
    "weight_multiplier": 0.95,
    "melee_damage":
                   ^
                    { "bash": 10 }
  },
  {

 FUNCTION : report_unvisited
 FILE     : D:\a\Cataclysm-BN\Cataclysm-BN\src\json.cpp
 LINE     : 125
 VERSION  : BN d109e74

**Comment by jackledead** [comment]
Noted. Will address asap

**Comment by jackledead** [comment]
Closed with https://github.com/jackledead/jackledead_armory/commit/49aabd483475ee9f27e4b05af01485eb4a7041c3

LMK how it goes.
